services:
  - type: web
    name: entropy-frontend
    env: node
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        value: https://proyecthacks.onrender.com
    healthCheckPath: /